import { csvInput } from './csvInterface';
export const restaurants: Array<csvInput> = 
[
    {
      "restaurantId": "6317637",
      "restaurantName": "Le Petit Souffle",
      "cuisines": "French, Japanese, Desserts",
      "avgCostForTwo": 1100,
      "currency": "Botswana Pula(P)",
      "hasTableBooking": "Yes",
      "hasOnlineDelivery": "No",
      "aggregateRating": 4.8,
      "ratingColor": "Dark Green",
      "ratingText": "Excellent",
      "votes": 314
    },
    {
      "restaurantId": "6304287",
      "restaurantName": "Izakaya Kikufuji",
      "cuisines": "Japanese",
      "avgCostForTwo": 1200,
      "currency": "Botswana Pula(P)",
      "hasTableBooking": "Yes",
      "hasOnlineDelivery": "No",
      "aggregateRating": 4.5,
      "ratingColor": "Dark Green",
      "ratingText": "Excellent",
      "votes": 591
    },
    {
      "restaurantId": "6300002",
      "restaurantName": "Heat - Edsa Shangri-La",
      "cuisines": "Seafood, Asian, Filipino, Indian",
      "avgCostForTwo": 4000,
      "currency": "Botswana Pula(P)",
      "hasTableBooking": "Yes",
      "hasOnlineDelivery": "No",
      "aggregateRating": 4.4,
      "ratingColor": "Green",
      "ratingText": "Very Good",
      "votes": 270
    },
    {
      "restaurantId": "6318506",
      "restaurantName": "Ooma",
      "cuisines": "Japanese, Sushi",
      "avgCostForTwo": 1500,
      "currency": "Botswana Pula(P)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 4.9,
      "ratingColor": "Dark Green",
      "ratingText": "Excellent",
      "votes": 365
    },
    {
      "restaurantId": "6314302",
      "restaurantName": "Sambo Kojin",
      "cuisines": "Japanese, Korean",
      "avgCostForTwo": 1500,
      "currency": "Botswana Pula(P)",
      "hasTableBooking": "Yes",
      "hasOnlineDelivery": "No",
      "aggregateRating": 4.8,
      "ratingColor": "Dark Green",
      "ratingText": "Excellent",
      "votes": 229
    },
    {
      "restaurantId": "18189371",
      "restaurantName": "Din Tai Fung",
      "cuisines": "Chinese",
      "avgCostForTwo": 1000,
      "currency": "Botswana Pula(P)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 4.4,
      "ratingColor": "Green",
      "ratingText": "Very Good",
      "votes": 336
    },
    {
      "restaurantId": "6300781",
      "restaurantName": "Buffet 101",
      "cuisines": "Asian, European",
      "avgCostForTwo": 2000,
      "currency": "Botswana Pula(P)",
      "hasTableBooking": "Yes",
      "hasOnlineDelivery": "No",
      "aggregateRating": 4,
      "ratingColor": "Green",
      "ratingText": "Very Good",
      "votes": 520
    },
    {
      "restaurantId": "6301290",
      "restaurantName": "Vikings",
      "cuisines": "Seafood, Filipino, Asian, European",
      "avgCostForTwo": 2000,
      "currency": "Botswana Pula(P)",
      "hasTableBooking": "Yes",
      "hasOnlineDelivery": "No",
      "aggregateRating": 4.2,
      "ratingColor": "Green",
      "ratingText": "Very Good",
      "votes": 677
    },
    {
      "restaurantId": "6300010",
      "restaurantName": "Spiral - Sofitel Philippine Plaza Manila",
      "cuisines": "European, Asian, Indian",
      "avgCostForTwo": 6000,
      "currency": "Botswana Pula(P)",
      "hasTableBooking": "Yes",
      "hasOnlineDelivery": "No",
      "aggregateRating": 4.9,
      "ratingColor": "Dark Green",
      "ratingText": "Excellent",
      "votes": 621
    },
    {
      "restaurantId": "6314987",
      "restaurantName": "Locavore",
      "cuisines": "Filipino",
      "avgCostForTwo": 1100,
      "currency": "Botswana Pula(P)",
      "hasTableBooking": "Yes",
      "hasOnlineDelivery": "No",
      "aggregateRating": 4.8,
      "ratingColor": "Dark Green",
      "ratingText": "Excellent",
      "votes": 532
    },
    {
      "restaurantId": "6309903",
      "restaurantName": "Silantro Fil-Mex",
      "cuisines": "Filipino, Mexican",
      "avgCostForTwo": 800,
      "currency": "Botswana Pula(P)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 4.9,
      "ratingColor": "Dark Green",
      "ratingText": "Excellent",
      "votes": 1070
    },
    {
      "restaurantId": "6309455",
      "restaurantName": "Mad Mark's Creamery & Good Eats",
      "cuisines": "American, Ice Cream, Desserts",
      "avgCostForTwo": 900,
      "currency": "Botswana Pula(P)",
      "hasTableBooking": "Yes",
      "hasOnlineDelivery": "No",
      "aggregateRating": 4.2,
      "ratingColor": "Green",
      "ratingText": "Very Good",
      "votes": 488
    },
    {
      "restaurantId": "6318433",
      "restaurantName": "Silantro Fil-Mex",
      "cuisines": "Filipino, Mexican",
      "avgCostForTwo": 800,
      "currency": "Botswana Pula(P)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 4.8,
      "ratingColor": "Dark Green",
      "ratingText": "Excellent",
      "votes": 294
    },
    {
      "restaurantId": "6310470",
      "restaurantName": "Guevarra's",
      "cuisines": "Filipino",
      "avgCostForTwo": 1000,
      "currency": "Botswana Pula(P)",
      "hasTableBooking": "Yes",
      "hasOnlineDelivery": "No",
      "aggregateRating": 4.2,
      "ratingColor": "Green",
      "ratingText": "Very Good",
      "votes": 458
    },
    {
      "restaurantId": "6314605",
      "restaurantName": "Sodam Korean Restaurant",
      "cuisines": "Korean",
      "avgCostForTwo": 700,
      "currency": "Botswana Pula(P)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 4.3,
      "ratingColor": "Green",
      "ratingText": "Very Good",
      "votes": 223
    },
    {
      "restaurantId": "18185059",
      "restaurantName": "Cafe Arabelle",
      "cuisines": "Cafe, American, Italian, Filipino",
      "avgCostForTwo": 800,
      "currency": "Botswana Pula(P)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 3.6,
      "ratingColor": "Yellow",
      "ratingText": "Good",
      "votes": 29
    },
    {
      "restaurantId": "18182702",
      "restaurantName": "Nonna's Pasta & Pizzeria",
      "cuisines": "Italian, Pizza",
      "avgCostForTwo": 850,
      "currency": "Botswana Pula(P)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 4,
      "ratingColor": "Green",
      "ratingText": "Very Good",
      "votes": 72
    },
    {
      "restaurantId": "6318213",
      "restaurantName": "Balay Dako",
      "cuisines": "Filipino",
      "avgCostForTwo": 1200,
      "currency": "Botswana Pula(P)",
      "hasTableBooking": "Yes",
      "hasOnlineDelivery": "No",
      "aggregateRating": 4.5,
      "ratingColor": "Dark Green",
      "ratingText": "Excellent",
      "votes": 211
    },
    {
      "restaurantId": "18255654",
      "restaurantName": "Hobing Korean Dessert Cafe",
      "cuisines": "Cafe, Korean, Desserts",
      "avgCostForTwo": 600,
      "currency": "Botswana Pula(P)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 4.5,
      "ratingColor": "Dark Green",
      "ratingText": "Excellent",
      "votes": 118
    },
    {
      "restaurantId": "6308205",
      "restaurantName": "Wildflour Cafe + Bakery",
      "cuisines": "Cafe, Bakery, American, Italian",
      "avgCostForTwo": 1500,
      "currency": "Botswana Pula(P)",
      "hasTableBooking": "Yes",
      "hasOnlineDelivery": "No",
      "aggregateRating": 4.4,
      "ratingColor": "Green",
      "ratingText": "Very Good",
      "votes": 392
    },
    {
      "restaurantId": "6315438",
      "restaurantName": "NIU by Vikings",
      "cuisines": "Seafood, American, Mediterranean, Japanese",
      "avgCostForTwo": 3000,
      "currency": "Botswana Pula(P)",
      "hasTableBooking": "Yes",
      "hasOnlineDelivery": "No",
      "aggregateRating": 4.7,
      "ratingColor": "Dark Green",
      "ratingText": "Excellent",
      "votes": 535
    },
    {
      "restaurantId": "6310406",
      "restaurantName": "The Food Hall by Todd English",
      "cuisines": "American, Asian, Italian, Seafood",
      "avgCostForTwo": 1800,
      "currency": "Botswana Pula(P)",
      "hasTableBooking": "Yes",
      "hasOnlineDelivery": "No",
      "aggregateRating": 4.5,
      "ratingColor": "Dark Green",
      "ratingText": "Excellent",
      "votes": 618
    },
    {
      "restaurantId": "6600681",
      "restaurantName": "Chez Michou",
      "cuisines": "Fast Food, French",
      "avgCostForTwo": 55,
      "currency": "Brazilian Real(R$)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 3,
      "ratingColor": "Orange",
      "ratingText": "Average",
      "votes": 6
    },
    {
      "restaurantId": "6601005",
      "restaurantName": "Cafe Daniel Briand",
      "cuisines": "Cafe",
      "avgCostForTwo": 30,
      "currency": "Brazilian Real(R$)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 3.8,
      "ratingColor": "Yellow",
      "ratingText": "Good",
      "votes": 9
    },
    {
      "restaurantId": "6600292",
      "restaurantName": "Casa do Biscoito Mineiro",
      "cuisines": "Bakery",
      "avgCostForTwo": 45,
      "currency": "Brazilian Real(R$)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 3.7,
      "ratingColor": "Yellow",
      "ratingText": "Good",
      "votes": 11
    },
    {
      "restaurantId": "6600441",
      "restaurantName": "Maori",
      "cuisines": "Brazilian",
      "avgCostForTwo": 60,
      "currency": "Brazilian Real(R$)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 3.8,
      "ratingColor": "Yellow",
      "ratingText": "Good",
      "votes": 11
    },
    {
      "restaurantId": "6600970",
      "restaurantName": "Pizza e Bessa",
      "cuisines": "Pizza",
      "avgCostForTwo": 50,
      "currency": "Brazilian Real(R$)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 3.2,
      "ratingColor": "Orange",
      "ratingText": "Average",
      "votes": 11
    },
    {
      "restaurantId": "6600379",
      "restaurantName": "Sushi Loko",
      "cuisines": "Japanese",
      "avgCostForTwo": 80,
      "currency": "Brazilian Real(R$)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 3.1,
      "ratingColor": "Orange",
      "ratingText": "Average",
      "votes": 10
    },
    {
      "restaurantId": "6600214",
      "restaurantName": "Beirute",
      "cuisines": "Arabian",
      "avgCostForTwo": 90,
      "currency": "Brazilian Real(R$)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 3.7,
      "ratingColor": "Yellow",
      "ratingText": "Good",
      "votes": 8
    },
    {
      "restaurantId": "6601218",
      "restaurantName": "New Koto",
      "cuisines": "Japanese",
      "avgCostForTwo": 200,
      "currency": "Brazilian Real(R$)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 3.7,
      "ratingColor": "Yellow",
      "ratingText": "Good",
      "votes": 5
    },
    {
      "restaurantId": "6600060",
      "restaurantName": "Sandubas Cafe",
      "cuisines": "Brazilian, Cafe",
      "avgCostForTwo": 30,
      "currency": "Brazilian Real(R$)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 0,
      "ratingColor": "White",
      "ratingText": "Not rated",
      "votes": 2
    },
    {
      "restaurantId": "6600083",
      "restaurantName": "Villa Tevere",
      "cuisines": "Italian",
      "avgCostForTwo": 150,
      "currency": "Brazilian Real(R$)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 4.1,
      "ratingColor": "Green",
      "ratingText": "Very Good",
      "votes": 12
    },
    {
      "restaurantId": "6601515",
      "restaurantName": "Rovereto",
      "cuisines": "Pizza",
      "avgCostForTwo": 100,
      "currency": "Brazilian Real(R$)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 3.1,
      "ratingColor": "Orange",
      "ratingText": "Average",
      "votes": 9
    },
    {
      "restaurantId": "6601361",
      "restaurantName": "Buena Carne",
      "cuisines": "Bar Food, Brazilian",
      "avgCostForTwo": 60,
      "currency": "Brazilian Real(R$)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 3.6,
      "ratingColor": "Yellow",
      "ratingText": "Good",
      "votes": 9
    },
    {
      "restaurantId": "6601602",
      "restaurantName": "Taco Pep",
      "cuisines": "Mexican, Grill",
      "avgCostForTwo": 100,
      "currency": "Brazilian Real(R$)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 4.3,
      "ratingColor": "Green",
      "ratingText": "Very Good",
      "votes": 29
    },
    {
      "restaurantId": "6601589",
      "restaurantName": "Coco Bambu",
      "cuisines": "International",
      "avgCostForTwo": 230,
      "currency": "Brazilian Real(R$)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 4.2,
      "ratingColor": "Green",
      "ratingText": "Very Good",
      "votes": 17
    },
    {
      "restaurantId": "6601862",
      "restaurantName": "Taype",
      "cuisines": "Peruvian, Latin American",
      "avgCostForTwo": 100,
      "currency": "Brazilian Real(R$)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 3.6,
      "ratingColor": "Yellow",
      "ratingText": "Good",
      "votes": 5
    },
    {
      "restaurantId": "6601595",
      "restaurantName": "Outback Steakhouse",
      "cuisines": "American, Grill",
      "avgCostForTwo": 150,
      "currency": "Brazilian Real(R$)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 4,
      "ratingColor": "Green",
      "ratingText": "Very Good",
      "votes": 10
    },
    {
      "restaurantId": "6601158",
      "restaurantName": "Manzue",
      "cuisines": "Seafood",
      "avgCostForTwo": 240,
      "currency": "Brazilian Real(R$)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 3.2,
      "ratingColor": "Orange",
      "ratingText": "Average",
      "votes": 6
    },
    {
      "restaurantId": "6600427",
      "restaurantName": "Coco Bambu",
      "cuisines": "International",
      "avgCostForTwo": 230,
      "currency": "Brazilian Real(R$)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 4.9,
      "ratingColor": "Dark Green",
      "ratingText": "Excellent",
      "votes": 30
    },
    {
      "restaurantId": "6600116",
      "restaurantName": "Gero",
      "cuisines": "Italian",
      "avgCostForTwo": 350,
      "currency": "Brazilian Real(R$)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 3.3,
      "ratingColor": "Orange",
      "ratingText": "Average",
      "votes": 8
    },
    {
      "restaurantId": "6601457",
      "restaurantName": "Brazilian American Burgers",
      "cuisines": "American, Burger",
      "avgCostForTwo": 50,
      "currency": "Brazilian Real(R$)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 3.6,
      "ratingColor": "Yellow",
      "ratingText": "Good",
      "votes": 9
    },
    {
      "restaurantId": "7303219",
      "restaurantName": "Pesqueiro Eco Gourmet",
      "cuisines": "Seafood, Bar Food, Brazilian",
      "avgCostForTwo": 140,
      "currency": "Brazilian Real(R$)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 4,
      "ratingColor": "Green",
      "ratingText": "Very Good",
      "votes": 7
    },
    {
      "restaurantId": "7304307",
      "restaurantName": "Confeitaria Colombo",
      "cuisines": "Desserts, Cafe",
      "avgCostForTwo": 100,
      "currency": "Brazilian Real(R$)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 4.8,
      "ratingColor": "Dark Green",
      "ratingText": "Excellent",
      "votes": 29
    },
    {
      "restaurantId": "7301215",
      "restaurantName": "Bibi",
      "cuisines": "Juices, Healthy Food",
      "avgCostForTwo": 60,
      "currency": "Brazilian Real(R$)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 4.7,
      "ratingColor": "Dark Green",
      "ratingText": "Excellent",
      "votes": 24
    },
    {
      "restaurantId": "7300596",
      "restaurantName": "Cervantes",
      "cuisines": "Beverages, Bar Food, Fast Food",
      "avgCostForTwo": 90,
      "currency": "Brazilian Real(R$)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 4.5,
      "ratingColor": "Dark Green",
      "ratingText": "Excellent",
      "votes": 29
    },
    {
      "restaurantId": "7300612",
      "restaurantName": "Amir",
      "cuisines": "Lebanese",
      "avgCostForTwo": 170,
      "currency": "Brazilian Real(R$)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 4.2,
      "ratingColor": "Green",
      "ratingText": "Very Good",
      "votes": 11
    },
    {
      "restaurantId": "7300704",
      "restaurantName": "TT Burger",
      "cuisines": "Burger",
      "avgCostForTwo": 60,
      "currency": "Brazilian Real(R$)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 4.8,
      "ratingColor": "Dark Green",
      "ratingText": "Excellent",
      "votes": 19
    },
    {
      "restaurantId": "7300955",
      "restaurantName": "Braseiro da Gevea",
      "cuisines": "Brazilian, Bar Food",
      "avgCostForTwo": 100,
      "currency": "Brazilian Real(R$)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 4.9,
      "ratingColor": "Dark Green",
      "ratingText": "Excellent",
      "votes": 40
    },
    {
      "restaurantId": "7300521",
      "restaurantName": "Balada Mix",
      "cuisines": "Brazilian, Healthy Food, Juices, Pizza",
      "avgCostForTwo": 90,
      "currency": "Brazilian Real(R$)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 4.6,
      "ratingColor": "Dark Green",
      "ratingText": "Excellent",
      "votes": 21
    },
    {
      "restaurantId": "7300515",
      "restaurantName": "Garota de Ipanema",
      "cuisines": "Brazilian, Bar Food",
      "avgCostForTwo": 120,
      "currency": "Brazilian Real(R$)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 4.9,
      "ratingColor": "Dark Green",
      "ratingText": "Excellent",
      "votes": 49
    },
    {
      "restaurantId": "7300483",
      "restaurantName": "Zaze Bistre Tropical",
      "cuisines": "Brazilian",
      "avgCostForTwo": 170,
      "currency": "Brazilian Real(R$)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 4.6,
      "ratingColor": "Dark Green",
      "ratingText": "Excellent",
      "votes": 21
    },
    {
      "restaurantId": "7301064",
      "restaurantName": "File de Ouro",
      "cuisines": "Brazilian",
      "avgCostForTwo": 90,
      "currency": "Brazilian Real(R$)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 4.3,
      "ratingColor": "Green",
      "ratingText": "Very Good",
      "votes": 14
    },
    {
      "restaurantId": "7304312",
      "restaurantName": "D.O.C Ristorante",
      "cuisines": "Italian",
      "avgCostForTwo": 150,
      "currency": "Brazilian Real(R$)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 4,
      "ratingColor": "Green",
      "ratingText": "Very Good",
      "votes": 5
    },
    {
      "restaurantId": "7300004",
      "restaurantName": "Sushi Leblon",
      "cuisines": "Japanese",
      "avgCostForTwo": 250,
      "currency": "Brazilian Real(R$)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 4.6,
      "ratingColor": "Dark Green",
      "ratingText": "Excellent",
      "votes": 25
    },
    {
      "restaurantId": "7300868",
      "restaurantName": "Talho Capixaba",
      "cuisines": "Bakery, Sandwich, Brazilian",
      "avgCostForTwo": 120,
      "currency": "Brazilian Real(R$)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 4.4,
      "ratingColor": "Green",
      "ratingText": "Very Good",
      "votes": 13
    },
    {
      "restaurantId": "7302637",
      "restaurantName": "Leme Light",
      "cuisines": "Brazilian",
      "avgCostForTwo": 40,
      "currency": "Brazilian Real(R$)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 4.2,
      "ratingColor": "Green",
      "ratingText": "Very Good",
      "votes": 7
    },
    {
      "restaurantId": "7302140",
      "restaurantName": "Shirley",
      "cuisines": "Brazilian, Seafood",
      "avgCostForTwo": 250,
      "currency": "Brazilian Real(R$)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 4.2,
      "ratingColor": "Green",
      "ratingText": "Very Good",
      "votes": 8
    },
    {
      "restaurantId": "7305048",
      "restaurantName": "Quiosque Chopp Brahma",
      "cuisines": "Bar Food, Brazilian",
      "avgCostForTwo": 70,
      "currency": "Brazilian Real(R$)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 0,
      "ratingColor": "White",
      "ratingText": "Not rated",
      "votes": 1
    },
    {
      "restaurantId": "7302898",
      "restaurantName": "Apraze_vel",
      "cuisines": "Brazilian",
      "avgCostForTwo": 300,
      "currency": "Brazilian Real(R$)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 4.7,
      "ratingColor": "Dark Green",
      "ratingText": "Excellent",
      "votes": 44
    },
    {
      "restaurantId": "7302859",
      "restaurantName": "Aconchego Carioca",
      "cuisines": "Brazilian, Bar Food",
      "avgCostForTwo": 85,
      "currency": "Brazilian Real(R$)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 4.6,
      "ratingColor": "Dark Green",
      "ratingText": "Excellent",
      "votes": 24
    },
    {
      "restaurantId": "7301700",
      "restaurantName": "Garota de Ipanema",
      "cuisines": "Brazilian, Bar Food",
      "avgCostForTwo": 80,
      "currency": "Brazilian Real(R$)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 4.3,
      "ratingColor": "Green",
      "ratingText": "Very Good",
      "votes": 10
    },
    {
      "restaurantId": "6706313",
      "restaurantName": "Cantina Famiglia Mancini",
      "cuisines": "Italian, Pizza",
      "avgCostForTwo": 250,
      "currency": "Brazilian Real(R$)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 4.5,
      "ratingColor": "Dark Green",
      "ratingText": "Excellent",
      "votes": 49
    },
    {
      "restaurantId": "6704326",
      "restaurantName": "Templo da Carne - Marcos Bassi",
      "cuisines": "Steak, BBQ",
      "avgCostForTwo": 250,
      "currency": "Brazilian Real(R$)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 4.4,
      "ratingColor": "Green",
      "ratingText": "Very Good",
      "votes": 17
    },
    {
      "restaurantId": "6711179",
      "restaurantName": "Gopala Hari",
      "cuisines": "Indian",
      "avgCostForTwo": 70,
      "currency": "Brazilian Real(R$)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 3.1,
      "ratingColor": "Orange",
      "ratingText": "Average",
      "votes": 5
    },
    {
      "restaurantId": "6702797",
      "restaurantName": "Jiquitaia",
      "cuisines": "Brazilian",
      "avgCostForTwo": 100,
      "currency": "Brazilian Real(R$)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 4.1,
      "ratingColor": "Green",
      "ratingText": "Very Good",
      "votes": 15
    },
    {
      "restaurantId": "6700475",
      "restaurantName": "Skye - Hotel Unique",
      "cuisines": "Beverages, International",
      "avgCostForTwo": 300,
      "currency": "Brazilian Real(R$)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 4.8,
      "ratingColor": "Dark Green",
      "ratingText": "Excellent",
      "votes": 59
    },
    {
      "restaurantId": "6713413",
      "restaurantName": "Les 3 Brasseurs",
      "cuisines": "French, Brazilian, Beverages",
      "avgCostForTwo": 120,
      "currency": "Brazilian Real(R$)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 4.6,
      "ratingColor": "Dark Green",
      "ratingText": "Excellent",
      "votes": 30
    },
    {
      "restaurantId": "6714340",
      "restaurantName": "Red Steak & Burger",
      "cuisines": "Brazilian, Grill",
      "avgCostForTwo": 75,
      "currency": "Brazilian Real(R$)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 3.9,
      "ratingColor": "Yellow",
      "ratingText": "Good",
      "votes": 5
    },
    {
      "restaurantId": "6710645",
      "restaurantName": "Cantinho da Gula",
      "cuisines": "Brazilian",
      "avgCostForTwo": 55,
      "currency": "Brazilian Real(R$)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 0,
      "ratingColor": "White",
      "ratingText": "Not rated",
      "votes": 0
    },
    {
      "restaurantId": "6700402",
      "restaurantName": "Paris 6 Classique",
      "cuisines": "French",
      "avgCostForTwo": 200,
      "currency": "Brazilian Real(R$)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 3.4,
      "ratingColor": "Orange",
      "ratingText": "Average",
      "votes": 73
    },
    {
      "restaurantId": "6700846",
      "restaurantName": "Kawa Sushi",
      "cuisines": "Sushi, Japanese",
      "avgCostForTwo": 120,
      "currency": "Brazilian Real(R$)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 3.5,
      "ratingColor": "Yellow",
      "ratingText": "Good",
      "votes": 9
    },
    {
      "restaurantId": "6702159",
      "restaurantName": "A Figueira Rubaiyat",
      "cuisines": "BBQ, Grill, Brazilian",
      "avgCostForTwo": 300,
      "currency": "Brazilian Real(R$)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 4.3,
      "ratingColor": "Green",
      "ratingText": "Very Good",
      "votes": 39
    },
    {
      "restaurantId": "6711666",
      "restaurantName": "Kinoshita",
      "cuisines": "Sushi",
      "avgCostForTwo": 230,
      "currency": "Brazilian Real(R$)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 3.9,
      "ratingColor": "Yellow",
      "ratingText": "Good",
      "votes": 12
    },
    {
      "restaurantId": "6701257",
      "restaurantName": "Meats",
      "cuisines": "Gourmet Fast Food, Burger",
      "avgCostForTwo": 120,
      "currency": "Brazilian Real(R$)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 4.3,
      "ratingColor": "Green",
      "ratingText": "Very Good",
      "votes": 68
    },
    {
      "restaurantId": "6706211",
      "restaurantName": "Paribar",
      "cuisines": "Brazilian, Italian",
      "avgCostForTwo": 150,
      "currency": "Brazilian Real(R$)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 4.3,
      "ratingColor": "Green",
      "ratingText": "Very Good",
      "votes": 46
    },
    {
      "restaurantId": "6705858",
      "restaurantName": "Terrae_o Itelia",
      "cuisines": "Italian",
      "avgCostForTwo": 400,
      "currency": "Brazilian Real(R$)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 4.4,
      "ratingColor": "Green",
      "ratingText": "Very Good",
      "votes": 37
    },
    {
      "restaurantId": "6701419",
      "restaurantName": "Divino Fogeo",
      "cuisines": "Brazilian, Mineira",
      "avgCostForTwo": 65,
      "currency": "Brazilian Real(R$)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 0,
      "ratingColor": "White",
      "ratingText": "Not rated",
      "votes": 2
    },
    {
      "restaurantId": "6703956",
      "restaurantName": "Super Grill",
      "cuisines": "Brazilian",
      "avgCostForTwo": 50,
      "currency": "Brazilian Real(R$)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 0,
      "ratingColor": "White",
      "ratingText": "Not rated",
      "votes": 2
    },
    {
      "restaurantId": "6709580",
      "restaurantName": "Esquina Mocote_",
      "cuisines": "Brazilian, North Eastern",
      "avgCostForTwo": 100,
      "currency": "Brazilian Real(R$)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 4.4,
      "ratingColor": "Green",
      "ratingText": "Very Good",
      "votes": 22
    },
    {
      "restaurantId": "6703176",
      "restaurantName": "Veloso",
      "cuisines": "Brazilian, Bar Food, Beverages",
      "avgCostForTwo": 70,
      "currency": "Brazilian Real(R$)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 4.6,
      "ratingColor": "Dark Green",
      "ratingText": "Excellent",
      "votes": 58
    },
    {
      "restaurantId": "6713772",
      "restaurantName": "Sainte Marie Gastronomia",
      "cuisines": "Lebanese, Arabian",
      "avgCostForTwo": 120,
      "currency": "Brazilian Real(R$)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 4.1,
      "ratingColor": "Green",
      "ratingText": "Very Good",
      "votes": 11
    },
    {
      "restaurantId": "17284404",
      "restaurantName": "Austin's BBQ and Oyster Bar",
      "cuisines": "BBQ, Burger, Seafood",
      "avgCostForTwo": 25,
      "currency": "Dollar($)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 3.3,
      "ratingColor": "Orange",
      "ratingText": "Average",
      "votes": 35
    },
    {
      "restaurantId": "17284203",
      "restaurantName": "BJ's Country Buffet",
      "cuisines": "American, BBQ",
      "avgCostForTwo": 10,
      "currency": "Dollar($)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 3.3,
      "ratingColor": "Orange",
      "ratingText": "Average",
      "votes": 25
    },
    {
      "restaurantId": "17284105",
      "restaurantName": "Cookie Shoppe",
      "cuisines": "",
      "avgCostForTwo": 0,
      "currency": "Dollar($)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 3.4,
      "ratingColor": "Orange",
      "ratingText": "Average",
      "votes": 34
    },
    {
      "restaurantId": "17284302",
      "restaurantName": "El Vaquero Mexican Restaurant",
      "cuisines": "Mexican",
      "avgCostForTwo": 0,
      "currency": "Dollar($)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 3.4,
      "ratingColor": "Orange",
      "ratingText": "Average",
      "votes": 45
    },
    {
      "restaurantId": "17284397",
      "restaurantName": "Elements Coffee Co - Northwest",
      "cuisines": "Coffee and Tea, Sandwich",
      "avgCostForTwo": 10,
      "currency": "Dollar($)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 3.4,
      "ratingColor": "Orange",
      "ratingText": "Average",
      "votes": 26
    },
    {
      "restaurantId": "17284211",
      "restaurantName": "Pearly's Famous Country Cookng",
      "cuisines": "",
      "avgCostForTwo": 0,
      "currency": "Dollar($)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 3.4,
      "ratingColor": "Orange",
      "ratingText": "Average",
      "votes": 36
    },
    {
      "restaurantId": "17284094",
      "restaurantName": "Chick-fil-A",
      "cuisines": "Fast Food",
      "avgCostForTwo": 10,
      "currency": "Dollar($)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 3.5,
      "ratingColor": "Yellow",
      "ratingText": "Good",
      "votes": 67
    },
    {
      "restaurantId": "17284409",
      "restaurantName": "Guang Zhou Chinese Restaurant",
      "cuisines": "Asian, Chinese, Vegetarian",
      "avgCostForTwo": 10,
      "currency": "Dollar($)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 3.9,
      "ratingColor": "Yellow",
      "ratingText": "Good",
      "votes": 141
    },
    {
      "restaurantId": "17284139",
      "restaurantName": "Harvest Moon",
      "cuisines": "Pizza, Bar Food, Sandwich",
      "avgCostForTwo": 25,
      "currency": "Dollar($)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 3.7,
      "ratingColor": "Yellow",
      "ratingText": "Good",
      "votes": 147
    },
    {
      "restaurantId": "17284403",
      "restaurantName": "Henry Campbell's Steakhouse",
      "cuisines": "Steak, Tapas, Bar Food",
      "avgCostForTwo": 70,
      "currency": "Dollar($)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 3.5,
      "ratingColor": "Yellow",
      "ratingText": "Good",
      "votes": 51
    },
    {
      "restaurantId": "17284145",
      "restaurantName": "Hong Kong Cafe",
      "cuisines": "Chinese, Seafood, Vegetarian",
      "avgCostForTwo": 25,
      "currency": "Dollar($)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 3.6,
      "ratingColor": "Yellow",
      "ratingText": "Good",
      "votes": 88
    },
    {
      "restaurantId": "17284150",
      "restaurantName": "House of China Restaurant II",
      "cuisines": "Chinese",
      "avgCostForTwo": 10,
      "currency": "Dollar($)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 3.8,
      "ratingColor": "Yellow",
      "ratingText": "Good",
      "votes": 153
    },
    {
      "restaurantId": "17284158",
      "restaurantName": "Jimmie's Hot Dogs",
      "cuisines": "",
      "avgCostForTwo": 10,
      "currency": "Dollar($)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 3.9,
      "ratingColor": "Yellow",
      "ratingText": "Good",
      "votes": 160
    },
    {
      "restaurantId": "17284175",
      "restaurantName": "Locos Grill & Pub",
      "cuisines": "American, Burger, Sandwich",
      "avgCostForTwo": 25,
      "currency": "Dollar($)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 3.5,
      "ratingColor": "Yellow",
      "ratingText": "Good",
      "votes": 57
    },
    {
      "restaurantId": "17284179",
      "restaurantName": "Longhorn Steakhouse",
      "cuisines": "American, Steak",
      "avgCostForTwo": 25,
      "currency": "Dollar($)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 3.5,
      "ratingColor": "Yellow",
      "ratingText": "Good",
      "votes": 58
    },
    {
      "restaurantId": "17284197",
      "restaurantName": "Mikata Japanese Steakhouse",
      "cuisines": "Japanese, Steak, Sushi",
      "avgCostForTwo": 40,
      "currency": "Dollar($)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 3.6,
      "ratingColor": "Yellow",
      "ratingText": "Good",
      "votes": 115
    },
    {
      "restaurantId": "17284241",
      "restaurantName": "Shogun Japanese Steak House",
      "cuisines": "Japanese, Steak, Sushi",
      "avgCostForTwo": 40,
      "currency": "Dollar($)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 3.5,
      "ratingColor": "Yellow",
      "ratingText": "Good",
      "votes": 51
    },
    {
      "restaurantId": "17284390",
      "restaurantName": "The Catch Seafood Room & Oyster Bar",
      "cuisines": "Seafood, Tapas, Bar Food",
      "avgCostForTwo": 40,
      "currency": "Dollar($)",
      "hasTableBooking": "No",
      "hasOnlineDelivery": "No",
      "aggregateRating": 3.8,
      "ratingColor": "Yellow",
      "ratingText": "Good",
      "votes": 250
    }
  ]